version: '3'

env:
  DOCKER_IMAGE: andreistefanciprian/pod-restarter-go
  APP_NAME: pod-restarter

tasks:

  # generate-pending-pods:
  #   cmds:
  #     - cd infra/tests; bash generate_pending_pods.sh

  uninstall:
    cmds:
      - helm uninstall --namespace default {{.APP_NAME}}

  build:
    cmds:
      - docker build -t {{.DOCKER_IMAGE}} . -f infra/Dockerfile
      - docker image push {{.DOCKER_IMAGE}}

  install:
    cmds:
      - helm template --namespace default --set image.digest={{.DOCKER_TAG}} {{.APP_NAME}} infra/helm_chart
      - helm upgrade --namespace default --install --set image.digest={{.DOCKER_TAG}} {{.APP_NAME}} infra/helm_chart
      
    vars:
      DOCKER_TAG:
        sh: docker image ls {{.DOCKER_IMAGE}} --digests | grep sha256 | awk '{print $3}' | head -n 1