{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pod_restarter.fullname" . }}
  labels:
    {{- include "pod_restarter.labels" . | nindent 4 }}
{{- end }}